version: '3.2'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=admin
            - POSTGRES_DB=database
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=123
        ports:
            - "8080:80"
        links:
            - db
    email-sender:
        build:
            context: backend/
            dockerfile: Dockerfile.EmailSender

        depends_on:
            - db-migration
    backend-api:
        build:
            context:  backend/
            dockerfile: Dockerfile.BackendApi
        ports:
            - "8888:5000"
        depends_on: 
            - db
    bot:
        build:
            context:  backend/
            dockerfile: Dockerfile.Bot
        depends_on: 
            - db
    bot:
        build:
            context:  backend/
            dockerfile: Dockerfile.UpdateResponsible
        depends_on: 
            - db
    db-migration:
        build:
            context: backend/
            dockerfile: Dockerfile.db
        depends_on:
            - db
